inc_file_path: "/tmp/vagrant-puppet/files" # Absolute path to the puppet template files directory (No need to change it)
tz: "America/Vancouver" # Timezone
user: "zee" # User to create
password: "whatisthepassword" # The user's password
project: "LSCS" # Django project folder or the name when you run django-admin.py startproject <PROJECT_NAME>
domain_name: "mzubair.ca/lscs" # Used in nginx, uwsgi and virtualenv directory
db_name: "LSCS_DB" #  database name to create
db_user: "LSCS_USER" #  username to create
db_password: "suchsecurepassword" #  password for the db_user
